"""empty message

Revision ID: 3672e70ee175
Revises: 72ab9ab76d9a
Create Date: 2017-11-21 02:01:12.909973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3672e70ee175'
down_revision = '72ab9ab76d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_receipt', sa.Column('provider', sa.String(length=45), nullable=True))
    op.drop_column('application_receipt', 'provider_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_receipt', sa.Column('provider_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('application_receipt', 'provider')
    # ### end Alembic commands ###
